server:
  port: 8888

spring:
  application:
    name: admin-service
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:4406/admin_db?autoReconnect=true&useSSL=false
    username: root
    password: root
    hikari:
      connection-timeout: 30000
      idle-timeout: 180000
      max-lifetime: 600000
      connection-init-sql: SELECT 1 FROM DUAL;
      connection-test-query: SELECT 2 FROM DUAL;
      minimum-idle: 5
      maximum-pool-size: 10
      validation-timeout: 5000
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  jackson:
    serialization:
      write_dates_as_timestamps: false
    mapper:
      default_view_inclusion: true
    default-property-inclusion: 'non_null'
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    baseline-on-migrate: true


db-core:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/birzha?autoReconnect=true&useSSL=false
    username: root
    password: root

