server:
  port: 8088

spring:
  db-core:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/clearslide?autoReconnect=true&useSSL=false
      username: root
    ssm:
      password-path:
  db-admin:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:4306/admin-db?autoReconnect=true&useSSL=false
      username: root
    ssm:
      password-path:

ssm:
  mode: develop

api:
  exchange:
    url: http://172.50.10.10:80/currency/rates
    username: varvatos
    password: qGbxQ466NWpB3W5G
  wallets:
    url: http://172.31.3.72:80/currencies
    username: varvatos
    password: qGbxQ466NWpB3W5G

scheduled:
  update:
    external-balances: 0 */5 * ? * *
    internal-balances: 0 */5 * ? * *