spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:4406/admin_db?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    scheme-name: admin_db
    hikari:
      connection-timeout: 30000
      idle-timeout: 180000
      max-lifetime: 600000
      connection-init-sql: SELECT 1 FROM DUAL;
      connection-test-query: SELECT 2 FROM DUAL;
      minimum-idle: 5
      maximum-pool-size: 10
      validation-timeout: 5000


#db-core:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/birzha?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true&useLegacyDatetimeCode=false&serverTimezone=UTC
#    username: root
#    password: root