export const fields = {
    user_id: 'User ID',
    email: 'Email',
    phone: 'Phone',
    messanger: 'Messenger',
    visit: 'Посещение',
    open_account: 'Открыт счет',
    new_account: 'Новый счет',
    new_account_not_refilled_48h: 'Новый счет не пополнен за 48 часов',
    new_account_not_refilled_7d: 'Новый счет не пополнен за 7 дней',
    new_account_not_refilled_30d: 'Новый счет не пополнен за 30 дней',
    new_account_not_refilled_90d: 'Новый счет не пополнен за 90 дней',
    refilled_first_time: 'Счет пополнен первый раз',
    refilled_first_time_48h: 'Счет пополнен, первая операция не совершена за 48 часов',
    refilled_first_time_7d: 'Счет пополнен, первая операция не совершена за 7 дней',
    refilled_first_time_30d: 'Счет пополнен, первая операция не совершена за 30 дней',
    refilled_first_time_90d: 'Счет пополнен, первая операция не совершена за 90 дней',
    account_replenished_first_operation: 'Пополнен аккаунт, совершена первая операция',
    active_client: 'Активный клиент',
    account_refilled_second_time: 'Аккаунт пополнен второй раз',
    recharge_basic: 'Пополнение Basic',
    recharge_profi: 'Пополнение Profi',
    recharge_gold: 'Пополнение Gold',
    recharge_executive: 'Пополнение Executive',
    bargaining_basic: 'Торги Basic',
    bargaining_profi: 'Торги Profi',
    bargaining_gold: 'Торги Gold',
    bargaining_executive: 'Торги Executive',
    no_bargaining: 'Нет торгов',
    client_not_trade_7d: 'Клиент не торгует 7 дней',
    client_not_trade_30d: 'Клиент не торгует 30 дней',
    client_not_trade_90d: 'Клиент не торгует 90 дней',
    client_not_trade_and_leaves: 'Клиент не торгует и уходит',
    client_not_trade_7d_withdraw_money:'Клиент не торгует 7 дней и вывел деньги',
    client_not_trade_30d_withdraw_money: 'Клиент не торгует 30 дней и вывел деньги',
    client_not_trade_90d_withdraw_money: 'Клиент не торгует 90 дней и вывел деньги',
    client_reset_balance: 'Клиент обнулил баланс',
    customer_resuscitation: 'Реанимация клиента',
    customer_activity: 'Активность клиента',
    client_active_30d: 'Клиент активен 30 дней',
    client_active_90d: 'Клиент активен 90 дней',
    client_active_1y: 'Клиент активен 1 год',
    client_active_3y: 'Клиент активен 3 года',
    client_active_5y: 'Клиент активен 5 лет'
  };
