export const fields = {
  user_id: 'User ID',
  deposit: 'Ввод (общая сумма в USD за все время)',
  withdrawal: 'Вывод (общая сумма в USD за все время)',
  deposit_more10: 'Ввод более $10 000',
  withdrawal_more10: 'Вывод более $10 000',
  commission_trading_per_day: 'Сумма комиссии (ТОРГИ) в $ за день',
  commission_transfer_per_day: 'Сумма комиссии (Внутр. ТРАНСФЕРА) в $ за день',
  commission_deposit_withdrawal_per_day: 'Сумма комиссии (ВВОД/ВЫВОД) в $ за день',
  commission_trading_per_week: 'Сумма комиссии (ТОРГИ) в $ за неделю',
  commission_transfer_per_week: 'Сумма комиссии (Внутр. ТРАНСФЕРА) в $ за неделю',
  commission_deposit_withdrawal_per_week: 'Сумма комиссии (ВВОД/ВЫВОД) в $ за неделю',
  commission_trading_per_month: 'Сумма комиссии (ТОРГИ) в $ за месяц',
  commission_transfer_per_month: 'Сумма комиссии (Внутр. ТРАНСФЕРА) в $ за месяц',
  commission_deposit_withdrawal_per_month: 'Сумма комиссии (ВВОД/ВЫВОД) в $ за месяц',
  change_balance_per_day: 'Изменение баланса за день',
  change_balance_per_week: 'Изменение баланса за неделю',
  change_balance_per_month: 'Изменение баланса за месяц',
  change_balance_per_year: 'Изменение баланса за год',
  number_transactions_per_day: 'Кол-во сделок за день',
  amount_transactions_per_day: 'Сумма сделок за день',
  number_transactions_per_day_flag: 'Кол-во сделок за день',
  amount_transactions_per_day_flag: 'Сумма сделок за день',
  number_transactions_per_week: 'Кол-во сделок за неделю',
  amount_transactions_per_week: 'Сумма сделок за неделю',
  number_transactions_per_week_flag: 'Кол-во сделок за неделю',
  amount_transactions_per_week_flag: 'Сумма сделок за неделю',
  number_transactions_per_month: 'Кол-во сделок за месяц',
  amount_transactions_per_month: 'Сумма сделок за месяц',
  number_transactions_per_month_flag: 'Кол-во сделок за месяц',
  amount_transactions_per_month_flag: 'Сумма сделок за месяц',
  number_transactions_per_year: 'Кол-во сделок за год',
  amount_transactions_per_year: 'Сумма сделок за год',
  number_transactions_per_year_flag: 'Кол-во сделок за год',
  amount_transactions_per_year_flag: 'Сумма сделок за год',
  no_deals_per_day: 'Сделки за день отсутствуют',
  no_deals_per_week: 'Сделки за неделю отсутствуют',
  no_deals_per_month: 'Сделки за месяц отсутствуют',
  no_deals_per_year: 'Сделки за год отсутствуют',
};