export const fields = {
  user_id: 'User ID',
  email: 'Email',
  deposit: 'Ввод (общая сумма в USD за все время)',
  withdrawal: 'Вывод (общая сумма в USD за все время)',
  deposit_more10: 'Ввод более $10 000',
  withdrawal_more10: 'Вывод более $10 000',
  commission_trading_per_day: 'Сумма комиссии (ТОРГИ) в $ за день',
  commission_transfer_per_day: 'Сумма комиссии (Внутр. ТРАНСФЕРА) в $ за день',
  commission_deposit_withdrawal_per_day: 'Сумма комиссии (ВВОД/ВЫВОД) в $ за день',
  commission_trading_per_week: 'Сумма комиссии (ТОРГИ) в $ за неделю',
  commission_transfer_per_week: 'Сумма комиссии (Внутр. ТРАНСФЕРА) в $ за неделю',
  commission_deposit_withdrawal_per_week: 'Сумма комиссии (ВВОД/ВЫВОД) в $ за неделю',
  commission_trading_per_month: 'Сумма комиссии (ТОРГИ) в $ за месяц',
  commission_transfer_per_month: 'Сумма комиссии (Внутр. ТРАНСФЕРА) в $ за месяц',
  commission_deposit_withdrawal_per_month: 'Сумма комиссии (ВВОД/ВЫВОД) в $ за месяц',
  commission_trading_per_year: 'Сумма комиссии (ТОРГИ) в $ за год',
  commission_transfer_per_year: 'Сумма комиссии (Внутр. ТРАНСФЕРА) в $ за год',
  commission_deposit_withdrawal_per_year: 'Сумма комиссии (ВВОД/ВЫВОД) в $ за год',
  change_balance_per_day: 'Изменение баланса за день',
  change_balance_per_week: 'Изменение баланса за неделю',
  change_balance_per_month: 'Изменение баланса за месяц',
  change_balance_per_year: 'Изменение баланса за год',
  trade_number_per_day: 'Кол-во сделок за день',
  trade_amount_per_day: 'Сумма сделок за день',
  trade_number_with_refill_per_day: 'Пополнения за день',
  trade_number_with_withdraw_per_day: 'Выводы за день',
  trade_number_per_week: 'Кол-во сделок за неделю',
  trade_amount_per_week: 'Сумма сделок за неделю',
  trade_number_with_refill_per_week: 'Пополнения за неделю',
  trade_number_with_withdraw_per_week: 'Выводы за неделю',
  trade_number_per_month: 'Кол-во сделок за месяц',
  trade_amount_per_month: 'Сумма сделок за месяц',
  trade_number_with_refill_per_month: 'Пополнения за месяц',
  trade_number_with_withdraw_per_month: 'Выводы за месяц',
  trade_number_per_year: 'Кол-во сделок за год',
  trade_amount_per_year: 'Сумма сделок за год',
  trade_number_with_refill_per_year: 'Пополнения за год',
  trade_number_with_withdraw_per_year: 'Выводы за год',
  no_deals_but_refilled_per_day: 'Сделки за день отсутствуют',
  no_deals_but_withdraw_and_refilled_per_day: 'Сделки за день отсутствуют',
  no_deals_but_refilled_per_week: 'Сделки за неделю отсутствуют',
  no_deals_but_withdraw_and_refilled_per_week: 'Сделки за неделю отсутствуют',
  no_deals_but_refilled_per_month: 'Сделки за месяц отсутствуют',
  no_deals_but_withdraw_and_refilled_per_month: 'Сделки за месяц отсутствуют',
  no_deals_but_refilled_per_year: 'Сделки за год отсутствуют',
  no_deals_but_withdraw_and_refilled_per_year: 'Сделки за год отсутствуют'
};