server:
  port: 6666


spring:
  application:
    name: admin-service
  jackson:
    serialization:
      write_dates_as_timestamps: false
    mapper:
      default_view_inclusion: true
    default-property-inclusion: 'non_null'
#  flyway:
#    url: ${db-admin.datasource.url}
#    user: ${db-admin.datasource.username}
#    password: ${db-admin.datasource.password}
#    baseline-on-migrate: true

db-admin:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:5506/admin_db?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
  ssm:
    password-path: admin

db-core:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://exdbdev.cedlveyttji9.us-east-2.rds.amazonaws.com:3306/dbdev2?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: exdevdb
  ssm:
    password-path: core

ssm:
  develop-mode: true

api:
  exchange:
    url: http://172.50.10.10:80/currency/rates
    username: varvatos
    password: qGbxQ466NWpB3W5G
  wallets:
    url: http://172.31.3.72:80/currencies
    username: varvatos
    password: qGbxQ466NWpB3W5G

scheduled:
  update:
    external-balances: 0 */5 * ? * *
    internal-balances: 0 */5 * ? * *
    rates-history: 0 0 * ? * *
    sync-transactions: 0 0 */3 * * *

sync:
  properties:
    transaction-chunk-size: 20


logging:
  file: /logs-light/admin.log
  level:
    me.exaretes.adminservice: DEBUG
    org.springframework: ERROR

angular:
  allowed:
    origins: http://localhost
