
spring:
  application:
    name: admin-service
  jackson:
    serialization:
      write_dates_as_timestamps: false
    mapper:
      default_view_inclusion: true
    default-property-inclusion: 'non_null'
  flyway:
    url: ${DB_ANDMIN_URL}
    user: ${DB_ANDMIN_USERNAME}
    password: ${db-admin.datasource.password}
    baseline-on-migrate: true

db-admin:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_ANDMIN_URL}
    username: ${DB_ANDMIN_USERNAME}
    password: ${DB_ANDMIN_PASSWORD}
  ssm:
    password-path: admin

db-core:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_CORE_URL}
    username: ${DB_CORE_USERNAME}
    password: ${DB_CORE_PASSWORD}
  ssm:
    password-path: core

ssm:
  develop-mode: true

api:
  exchange:
    url: http://172.50.10.10:80/currency/rates
    username: ${API_EXCHANGE_USERNAME}
    password: ${API_EXCHANGE_PASSWORD}
  wallets:
    url: http://172.31.3.72:80/currencies
    username: ${API_WALLETS_USERNAME}
    password: ${API_WALLETS_PASSWORD}

scheduled:
  update:
    external-balances: 0 */5 * ? * *
    internal-balances: 0 */5 * ? * *
    rates-history: 0 0 * ? * *
    sync-transactions: 0 0 */3 * * *

sync:
  properties:
    transaction-chunk-size: 20


logging:
  file: /logs-light/admin.log
  level:
    me.exaretes.adminservice: DEBUG
    org.springframework: ERROR

angular:
  allowed:
    origins: ${placeholder}
