spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3406/admin_db_test?autoReconnect=true&useSSL=false&rewriteBatchedStatements=true&lower_case_table_names=1&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    scheme-name: admin_db_test
    hikari:
      connection-timeout: 1000
      idle-timeout: 180000
      max-lifetime: 600000
      connection-init-sql: SELECT 1 FROM DUAL;
      connection-test-query: SELECT 2 FROM DUAL;
      minimum-idle: 5
      maximum-pool-size: 10
      validation-timeout: 5000
#  flyway:
#    url: ${spring.datasource.url}
#    user: ${spring.datasource.username}
#    password: ${spring.datasource.password}
#    baseline-on-migrate: true

db-core:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/birzha_empty_schema?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root

logging:
  level:
    me.exrates.adminservice: debug
